# Generated by Django 4.1.1 on 2023-01-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pages_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=14)),
                ('message', models.TextField()),
            ],
        ),
    ]
